import pandas as pd
import numpy as np
import seaborn as sns
from transformers import AutoTokenizer
from datetime import datetime
import os
import sys
import re


from peft import (
    LoraConfig,
    PeftConfig,
    get_peft_model,
    get_peft_model_state_dict,
#    prepare_model_for_int8_training,
    prepare_model_for_kbit_training,
    set_peft_model_state_dict,
    PeftModel
)
from transformers import BitsAndBytesConfig
from transformers import AutoTokenizer, AutoModelForCausalLM

def generate_response(prompt,lora,tokeniser,model):
  '''
  Generating response from teh model. The Lora parameter is a binary value to activate
  or deactivate trained lora adopters.
  '''
  if lora:
    model.enable_adapter_layers()
  else:
    model.disable_adapter_layers()
  loaded_tokenizer = tokeniser

  # max_input_length = model.config.max_position_embeddings
  max_input_length = 1000
  # print(max_input_length)

  inputs = loaded_tokenizer(prompt, return_tensors="pt",truncation=True, padding=True, max_length=max_input_length,add_special_tokens=True).to(model.device)

  # Generate predictions
  generated_ids = model.generate(**inputs,max_new_tokens=2000)

  # Decode the generated output
  generated_text = loaded_tokenizer.decode(generated_ids[0], skip_special_tokens=True)

  print(generated_text)
  return generated_text



def base_prompt_format(question,note=""):
  '''
  Base prompt for generating logical steps
  '''
  return f"""### Instruction:
    Use the Task below and the Input given to write the Response:

    ### Task:
    Consider yourself as a helpful tutor for python learners. Consider the learner has only basic programming knowledge. Your task is to break down the given coding problem into its simple logical functional steps. Make sure each step is well explained and logical and accordance to solve the problem.
    Below is a sample of output structure which is expected.
    ### Structure of the expected output:
    Response:
    Step 1: <explanation of step1> along with Reason
    Step 2: <explanation of step2> along with Reason
    ...

    Below is the problem you need to provide logical steps following above instruction.
    ### Input:
    {question}

    {note}
    Dont provide direct code for the given problem..
    <prompt_end>
    """

def code(text):
  '''
  Extracting code from generated response using predefined python token.
  '''
  mat = re.search(r"<prompt_end>\n(.*)", text, re.DOTALL)
  #print(mat)
  if mat:
    resp = mat.group(1)
    #print(resp)
    mat1 = re.search(r"```python\n(.*)```", resp, re.DOTALL)
    mat2 = re.search(r"'''python\n(.*)'''", resp, re.DOTALL)
    if mat1:
      python_code = mat.group(1)
      return python_code
    elif mat2:
      python_code = mat2.group(1)
      return python_code
    else:
      return 0
  else:
    return 0

def ins(text):
  '''
  Extracting only the instruction from the model generated response.
  '''
  mat = re.search(r"<prompt_end>\n(.*)", text, re.DOTALL)
  #print(mat)
  if mat:
    resp = mat.group(1)
    mat1 = re.search(r"### Response:(\s*?)\n(.*)```python", resp, re.DOTALL)
    mat2 = re.search(r"Response:\n(.*)", resp, re.DOTALL)
    #print(mat)
    if mat1:
      inst = mat.group(1)
      return inst
    elif mat2:
      inst = mat2.group(1)
      return inst
    else:
      return 0
  else:
    return 0

def ans(text):
  '''
  Extracting only text generated by model after removing the input prompt from
  model generation using <prompt_end> tag.
  '''
  mat = re.search(r"<prompt_end>\n(.*)", text, re.DOTALL)
  #print(mat)
  if mat:
    return mat.group(1)
  else:
    return 0

def code_prompt_format(problem,response,ques,code):
  '''
  Prompt format for ask question button.
  '''
  return f"""### Instruction:
    Use the Task below and the Input given to write the Response:

    ### Task:
    Consider yourself as a helpful coding assistant and you are interacting with a learner studying python programming. You have already provided the Break down of the below coding problem. considering the response provided Write detailed explanation for the query asked by learner and include python code samples for the question asked by learner if necessary.

    Consider below is the problem statement and response provided to learner.
    Provide detailed explanation of how to implement learners question even it is a repeated explanation.

    ### Problem Statement:
    {problem}

    ### Response Provided:
    {response}

    ### Code written by learner:
    {code}

    Explain the concept thoroughly, including Python examples if needed, while ensuring no direct solutions to the problem statement are included. If necessary, illustrate the concept using pseudocode or unrelated examples. Also at end please provide a hint in 2 line of how the student should proceed considering the code he/she has written. If there is no code ask user to write the code for step 1 gently by giving some hint. Address the learner as you.

    ### Explanation required for question - {ques}

    Dont provide a direct code to the problem statement given in Problem Statement
    <prompt_end>
    """

def generate_answer_parllel(ques,response,question,tokeniser,model,code):
    ques_prompt=code_prompt_format(ques,str(response),question,code)
    resp = generate_response(ques_prompt,True,tokeniser,model)
    return ans(resp)
